### ISSUE TITLE
30 errors upon trying to run npm run build

### ISSUE THREAD

**Issue by emmfreak** [claabs/markov-discord#10]
Not sure what happened or where I've gone wrong. Most seem to be module or namespace errors. Here's the log: 
[2020-05-26T21_00_45_408Z-debug.log](https://github.com/claabs/markov-discord/files/4685032/2020-05-26T21_00_45_408Z-debug.log)

**Comment by claabs** [comment]
I can't seem to recreate this. It doesn't look like it's failing to find `tsc`, but instead that `tsc` is failing the build. Is there log output from `tsc` that you can provide?

Other than that, the only suggestion I have is delete your `node_modules` and `npm i` again, making sure that it installs correctly.
