### ISSUE TITLE
Retaining messages

### ISSUE THREAD

**Issue by weedoe** [claabs/markov-discord#13]
I have multiple servers that I want to train the bot in, however, it only seems to save chats from one server at a time. I'm fine with excessive processing. Does it require a simple change in the code in order to retain messages across servers?

**Comment by claabs** [comment]
This is one of the major missing features. 

You can invite the bot to multiple servers, however the language database will merge between the two. This will potentially leak info between two servers, so don't do it if you want them to be private from each other.

If you want separate language databases, you'll need to run multiple instances of it from separate folders to isolate the databases.

**Comment by claabs** [comment]
Sorry, I just realized why it's doesn't work with multiple servers. The train command overwrites the existing database. You could merge them manually by training each separately and just concatenating the JSON database arrays. If you never train again, it should work fine from there.

**Comment by weedoe** [comment]
Hmm, never thought of doing that. I would go with that but I was wanting to update the database every so often in my main discord server so that new messages could be included in the database while still including messages from other servers.

**Comment by claabs** [comment]
If the bot is running, any new messages sent are automatically added to the database, so it should be fine. The train command is only for setup to load in the channel history.

**Comment by weedoe** [comment]
Ah, I'll try that then. Thanks!

**Comment by maghikal** [comment]
Would you consider adding a feature to not overwrite the existing database? I wanted to train the bot to multiple channels in the same server but it limits itself to the channel you call the train command in. 

I don't know how to concatenate the database arrays, but i can experiment figuring it out. Unless you wouldn't mind giving me a quick guide :)

**Comment by claabs** [comment]
Yeah, training from multiple channels is a major lacking feature. I really only tailored it for my own Discord server's use case.

As for concatenating multiple channel databases, it should be pretty simple if I remember how the program works:

1. Train in a channel
2. Rename the `markovDB.json` to something else (like `markov-channel-A.json`)
3. Delete `markov.json`
4. Repeat steps 1-3 for all the channels
5. You should be able to manually concatenate the `messages` arrays in the channel DBs. (scripting this would probably be pretty simple if you're able)
```json
{
    "messages": [ <channel A messages>, <channel B messages>, <etc...>]
}

```

**Comment by maghikal** [comment]
ah great so i don't need to bother with the giant one, it seemed like it was regenerating on every start anyway. Thank you! I'll give it a shot
