### ISSUE TITLE
Feature request: support for threads

### ISSUE THREAD

**Issue by felda** [claabs/markov-discord#23]
In late August, 2021 threads were added to Discord. I can get Markov-bot into a thread by mentioning it by name, but it is not capable of responding in that thread. Can we get support for threads?

https://support.discord.com/hc/en-us/articles/4403205878423-Threads-FAQ

**Comment by claabs** [comment]
Added in [v2.0](https://github.com/claabs/markov-discord/releases/tag/v2.0.0)
