### ISSUE TITLE
Docker issue

### ISSUE THREAD

**Issue by salutemyboot** [claabs/markov-discord#45]
i have tried multiple things all day, when I copy and paste docker run --restart unless-stopped --rm -ti -v /my/host/dir:/usr/app/config ghcr.io/claabs/markov-discord:latest
in the terminal I get this error
docker: Conflicting options: --restart and --rm.

**Comment by claabs** [comment]
Fixed in https://github.com/claabs/markov-discord/commit/d3a3555a50c33bf035d124d00d0737f3a888fa40
